def yardmap():
  print("____________________________________________________________________________________      ________________")
  print("|                                                                                     ^                  |")
  print("|                                                                                     |                  |")
  print("|                                                                              Gate to Garden            |")
  print("|                                                                                                        |")
  print("|                           Yard                                                          Security  ____|")
  print("|                                                                                          Gate     |  ")
  print("|                                                                                          To     ->|")
  print("|                                                                                          House    |")
  print("|_________________________                                                                          |____")
  print("                          |                                              You are Here                   |")
  print("                          |                                                 |                            |")
  print("                          |                                                 V                            |")
  print("                          |_____________________________________________    X    ________________________|") 
def gardenmap():
  print("____________________________________________________________________________________")
  print("|                                                                                   |")
  print("|                                                                    Stairs          ")
  print("|                                                                       To     ->    ")
  print("|                                                                    Cellar          ")
  print("|                                                                                    |")
  print("|      Garden                                                     Balcony            |")
  print("|                                                                       |           |")
  print("|                                                                       V           |")
  print("|                                                               ____________________|")
  print("|                                                               |                    ")
  print("|                                                               |                    ")
  print("|                                                               |                    ")
  print("|                                                               |                    ")
  print("|                                      Gate to Yard             |                    ")
  print("|                                           |                   |                    ")
  print("|                                           V                   |                    ")
  print("|                                                               |                    ")
  print("|______________________________________           ______________|                    ")
def lowerManorMap():
  print("___________________________________________________________")
  print("|                      |                                  |")
  print("|                      |                                  |")
  print("|                      |              ____________________|")
  print("|                      |             |                    |")
  print("|                      |             |                    |")
  print("|                      |             |                    |")
  print("|                      |             |                    |")
  print("|                             ^                           |")
  print("                              |                            ")
  print("     Entrance               Stairs          Entrance       ")
  print("  <-  To                                       To     - >  ")
  print("      Library                              Dining Hall     ")
  print("                                                           ")
  print("|                                                         |")
  print("|                                                         |")
  print("|                                                         |")
  print("|                                                         |")
  print("|                                                         |")
  print("|                               Entrance to Manor         |")
  print("|                                        |                |")
  print("|                                        V                |")
  print("|____________________________________        _____________|")
print("Welcome to The Ring.")
print("Type start to begin.")
start = input()
if start.lower().strip() == "start":
  print("You, a high ranking member of the royal guard, are tasked with stealing back a priceless ring form a greedy jeweler named Lucuius.")
  print("With this being a difficult task you've been given many tools to help you along the way.")
  print("Type ok to continue.")
else:
  print("Invalid Choice.")
  exit()
Ok = input()
if Ok.lower().strip() == "ok":
  print("It is known that this jeweler is holding a party for the wealthy tonight, it will be of the best choice for you to be stealthy about your approach.")
  print("You arrive by the gate and observe the area, pondering how you should begin.")
else:
  print("Invalid Choice.")
  exit()
yardmap()
print("Choices:")
print("1. Go to Garden.\n2. Stay in Yard.\n3. Go to the Security Gate.")
startchoice = input(">")
if startchoice.lower().strip() == "1":
  print("\nYou walk over through the gates and to the garden, halting near a bench to observe the garden and the side of the house.\nYou notice that there is an open balcony and a stairway down to a cellar underneath the house.\nChoices:\n1. Go through the balcony.\n2. Go down into the cellar.")
  gardenmap()
  pathway1_choice1 = input(">")
  if pathway1_choice1.lower().strip() == "1":
    print("\nYou climb up on a pillar and jump to the balcony, grabbing the railing and pulling yourself up onto the balcony and moving inside to room.\nYou leave the room and wander a bit on the upper floors until you come up near a guard facing the opposite way of you.\n\nChoices:\n1. Knock the guard out.\n2. Hide and wait for the guard to pass.")
    pathway1_choice2 = input(">")
    if pathway1_choice2.lower().strip() == "2":
      print("You enter the cellar going down the stairs")
elif startchoice.lower().strip() == "2":
  print("You choose to stay in the yard for a bit, waiting around.")
  print("After a bit you notice a letter blow over near you, you pick it up and dust it off, it reads.")
  print("_______________________________")
  print("|   Dear Reciever,            |")
  print("|     You have been invited   |")
  print("|     to a party this evening |")
  print("|     at the Manor of Lucius. |")
  print("|     I'm looking forward to  |")
  print("|      seeing you there       |")
  print("|      tomorrow night!        |")
  print("|                             |")
  print("|                             |")
  print("|                             |")
  print("|                             |")
  print("|                             |")
  print("|                             |")
  print("|                 From        |")
  print("|                   Lucius.   |")
  print("|                             |")
  print("|_____________________________|")
  print("You go back to the secuirty guard and show him the letter.\n He nods, opens the gate, and lets you pass.\nYou enter the manor and are met with multiple areas to enter.\nChoices:\n1. Go Upstairs\n2. Go into the Library.")
  lowerManorMap()
  pathway2_choice1 = input(">")
  if pathway2_choice1.lower().strip() == "1":
    print("You go up the stairs, passing by multiple others guests as you make your way to to seperate rooms to enter, one on your right and one on your left.")
elif startchoice.lower().strip() == "3":
  print("You head over to the security gate only to be stopped by the guard who asks you for your invitation paper.")
  print("Knowing you don't have one you go back to where you were, looking around.\n A bottle rolls by you and stops after hitting a small rock next to you.\nChoices:\n1. Throw the Rock.\n2. Throw the Bottle.")
  pathway3_choice1 = input(">")
  if pathway3_choice1 == "1":
    print("You throw the rock near the gate to the garden and the guard leaves his post.\nYou sneak past the security gate while the guard is distracted.")
  elif pathway3_choice1 == "2":
    print("You grab the bottle and throw it near the gate to the garden, the guard leaves his post following the loud shatter.\nYou run through the security gate while the guard is distracted.") 
  else:
    print("Invalid Choice.")
    exit() 
  print("Once you've gotten through the gate you make your way into the manor, stepping foot into the party.\nYou are met with multiple ways to go.\nChoices:\n1. Go Upstairs\n2. Go into the dining hall.")
  lowerManorMap()
  pathway3_choice2 = input(">")
  if pathway3_choice2 == "1":
    print("You go upstairs and you are eventually met with two doors to go through.\nChoices:\n1. Left Door\n2. Right Door")
  elif pathway3_choice2 == "2":
    print("You go into the dining hall, looking around the area for a ring being held anywhere within there.\n") 
else:
  print("Invalid Choice.")
  exit()
